channels:
- conda-forge
dependencies:
- python=3.12.2
- pip<=25.0.1
- pip:
  - mlflow==3.1.1
  - cffi==1.16.0
  - cloudpickle==3.1.1
  - defusedxml==0.7.1
  - dill==0.3.8
  - numpy==1.26.4
  - pandas==2.2.3
  - torch==2.7.1
  - torchvision==0.22.1
  - tqdm==4.66.5
name: mlflow-env
