name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        token_format: 'access_token'
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install test dependencies
      run: |
        pip install -r requirements-dev.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=." >> $GITHUB_ENV

    - name: Run tests
      run: |
        pytest --cov=src --cov-report=term-missing tests

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Set Docker image name
      run: echo "DOCKER_IMAGE=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/automl/automl-cv-api" >> $GITHUB_ENV

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Verify image push
      run: |
        gcloud artifacts docker images list us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/automl/automl-cv-api \
        --filter="package=automl-cv-api" --format="table(name, updateTime)"

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE }} \
          --image ${{ env.DOCKER_IMAGE }}:${{ github.sha }} \
          --platform managed \
          --region ${{ secrets.CLOUD_RUN_REGION }} \
          --service-account ${{ secrets.GCP_SERVICE_ACCOUNT }} \
          --allow-unauthenticated \
          --timeout=600s \
          --port=8080 \
          --memory=1Gi \
          --quiet