name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install test dependencies
      run: |
        pip install -r requirements-dev.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=." >> $GITHUB_ENV

    - name: Run tests
      run: |
        pytest --cov=src --cov-report=term-missing tests

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and Push Docker Image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/automl/automl-cv-api .
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/automl/automl-cv-api

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ${{ secrets.CLOUD_RUN_SERVICE }}
        region: ${{ secrets.CLOUD_RUN_REGION }}
        image: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/automl/automl-cv-api
        service_account: github-actions@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com